#include "../main.h"
#include <stdio.h>
#include <limits.h>
int main(void)
{
    _printf("[%x]\n", USHRT_MAX);
    printf("[%x]\n", USHRT_MAX);
    _printf("[%5x]\n", USHRT_MAX);
    printf("[%5x]\n", USHRT_MAX);
    _printf("[%15x]\n", USHRT_MAX);
    printf("[%15x]\n", USHRT_MAX);
    _printf("[%-15x]\n", USHRT_MAX);
    printf("[%-15x]\n", USHRT_MAX);
    _printf("[%#15x]\n", USHRT_MAX);
    printf("[%#15x]\n", USHRT_MAX);
    _printf("[%#-15x]\n", USHRT_MAX);
    printf("[%#-15x]\n", USHRT_MAX);
    _printf("[%c]\n", 65);
    printf("[%c]\n", 65);
    _printf("[%5c]\n", 65);
    printf("[%5c]\n", 65);
    _printf("[%-5c]\n", 65);
    printf("[%-5c]\n", 65);
    _printf("[%s]\n", "Felix");
    printf("[%s]\n", "Felix");
    _printf("[%10s]\n", "Felix");
    printf("[%10s]\n", "Felix");
    _printf("[%-10s]\n", "Felix");
    printf("[%-10s]\n", "Felix");
    return (0);
}
